adding the hero section to the team page
Junior-Developer-Group/junior-developer-group pull request #7
Opened 2021-05-28 09:47 UTC by Denice-S

created a teamPage.html file 
created a teamPage.css file
created the hero section for desktop and mobile as per the figma file

The intention will be to rename these files once the dashboard bit is separated out.

And feedback welcome good or bad!

2021-06-02 14:21 UTC, onlyasmalllizard requested changes
Hi Denice,

This looks really good, you've really matched the Figma!

We actually have two versions of the logo, and this is the one meant to be put on dark backgrounds. I'll send you the one for light backgrounds on Discord. I think it will look better without having white on top of a slightly different shade of white!

Also on looks, would you be able to nudge the "Read More" text shadow up a little on the Y axis? I feel like I'm seeing the letters again too distinctly, which makes it a little hard to read.

There's a weird no-mans-land between tablet sizes and fullscreen on a laptop where the h1 splits onto multiple lines and the lines overlap.

This is a very nit-picky comment, but from what I can tell, ".hero_info h1" is styling the same element that you style within media queries as ".hero h1". I would suggest using the same selector throughout so that we can tell that they're the same thing.

This last point is just a suggestion and I don't mind if you decide to ignore it. Right now you have the media queries going by max-width, meaning that outside of media queries is the CSS for computers and then each media query styles for smaller and smaller devices. I think it might be easier to format these in a mobile-first style, having the CSS for the smallest screens outside of the media queries and setting changes within media queries for larger screens using min-width. Right now, I'm seeing several rules being set multiple times within media queries. If you did it the other way around, I think you wouldn't need to do this so often.

An example is the rule ".hero { padding: 1.8em; }". This is set separately in all but one media query. if you had it in a min-width media query, this rule would bubble up until you got to the media query for your largest screen size (screens larger than 64.5em), where you could set it back to 4em.

2021-06-06 13:20 UTC, Denice-S commented
Hey , thanks for reviewing. Okay so I have attempted to re organise this so it is mobile first and the smallest screens are targeted outside of the media queries and as you get  bigger screen sizes they are targeted in the media queries.

Please feel free to feedback as I am not so good at this. 

I have also adjusted the call to action link with the shadow and hopefully this is better? i personally hate the shadow but i was following the figma design.

the original figma file is using the old logo which is not transparent (looks like it is a grey background), but i have used the transparent one you gave me so see what you think.

2021-06-09 19:19 UTC, mateahoward submitted a review, later dismissed

2021-06-09 19:25 UTC, mateahoward approved these changes

2021-06-09 19:26 UTC, merged